// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Optional: only needed if the Postgres server's `template1` isn't pristine
    // (e.g. it doubles as the app's own database), which would otherwise leak
    // existing objects into Prisma's auto-created shadow database.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
